exclude:
- /exalteredpp/thirdparty/.*
- /exalteredpp/src/qt/.*
- /exalteredpp/headers/qt/.*

languages:
- name: cpp
  production:
    exclude:
      - /exalteredpp/src/test-case/.*\.cpp
  test:
    include:
      - /exalteredpp/src/test-case/.*\.cpp

component_depth: 6
