exclude:
- /core/thirdparty/.*
- /core/headers/.*

languages:
- name: cpp
  production:
    exclude:
      - /core/src/test-case/.*\.cpp
  test:
    include:
      - /core/src/test-case/.*\.cpp

component_depth: 4
