exclude:
- /exalteredpp/thirdparty/.*

languages:
- name: cpp
  production:
    exclude:
      - /exalteredpp/src/test-case/.*\.cpp
  test:
    include:
      - /exalteredpp/src/test-case/.*\.cpp

component_depth: 6
