exclude:
- /exalteredpp/thirdparty/.*
- /exalteredpp/src/qt/.*
- /exalteredpp/src/qt-test/.*
- /exalteredpp/headers/.*

languages:
- name: cpp
  production:
    exclude:
      - /exalteredpp/src/test-case/.*\.cpp
  test:
    include:
      - /exalteredpp/src/test-case/.*\.cpp

component_depth: 4
