language: cpp
dist: xenial
compiler: g++
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_install:

install:

script:
  - cd core
  - export CSTD=c++14
  - make -f build/Makefile test
  - chmod 777 test
  - ./test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
