language: cpp
dist: trusty
compiler: g++
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_install:

install:
  - sudo apt-get update && \
  - sudo apt-get install build-essential software-properties-common -y && \
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
  - sudo apt-get update && \
  - sudo apt-get install gcc-6 g++-6 -y && \
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6 && \
  - g++ -v

script:
  - cd core
  - export CSTD=c++1y
  - make -f build/Makefile test
  - chmod 777 test
  - ./test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
