language: cpp
dist: trusty
compiler: g++
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
    sudo apt-get update -y

install:
    sudo apt-get install -y mingw-w64

script:
  - cd core/build/
  - mingw32-make -f Makefile test
  - chmod 777 test
  - ./test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
