language: cpp
dist: trusty
compiler: g++
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_install:

install:
  - sudo apt-get install -y gcc-6
  - g++ -v

script:
  - cd core
  - export CSTD=c++1y
  - make -f build/Makefile test
  - chmod 777 test
  - ./test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
