language: cpp
dist: trusty
compiler: g++
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_install:

install:

script:
  - cd core/build/
  - export CSTD=c++1y
  - make -f Makefile test
  - chmod 777 test
  - ./test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
